---
- name: Prepare Installation on a Clean Server
  become: true

- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Install git package
  yum:
    name: git
    state: present

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Install podman-compose
  pip:
    name: podman-compose
    state: present
    executable: pip3
    extra_args: --user --force-reinstall
  
- name: Kill firewall
  service:
    name: firewalld
    enabled: no
        state: stopped

