---
- name: Prepare Conjur Server with Repo
  hosts: nodes
  roles: 
    - common
  
  tasks:
    - name: Clone Conjur Quickstart repository
      git:
        repo: https://github.com/gclim/conjur-quickstart.git
        dest: ./conjur
        clone: yes
